"""empty message

Revision ID: 7d67a6a14a11
Revises: 0876e2018902
Create Date: 2020-10-18 16:03:02.404825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d67a6a14a11'
down_revision = '0876e2018902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('feature', sa.String(length=128), nullable=True),
    sa.Column('tell', sa.String(length=128), nullable=True),
    sa.Column('business_hours1', sa.String(length=128), nullable=True),
    sa.Column('business_hours2', sa.String(length=128), nullable=True),
    sa.Column('regular_holiday', sa.String(length=128), nullable=True),
    sa.Column('place', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('comments', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurants')
    # ### end Alembic commands ###
